### ISSUE TITLE
type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by dishant-livebird** [leanflutter/flutter_distributor#127]
While make deb package using "flutter_distributor package --platform linux --targets deb" this command .

type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      FlutterDistributor.distributeOptions (package:flutter_distributor/src/flutter_distributor.dart:67:16)
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:138:35)
#2      CommandPackage.run (file:///home/ubuntu/.pub-cache/hosted/pub.dartlang.org/flutter_distributor-0.3.1/bin/command_package.dart:131:24)
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#4      main (file:///home/ubuntu/.pub-cache/hosted/pub.dartlang.org/flutter_distributor-0.3.1/bin/main.dart:47:17)
<asynchronous suspension>

**Comment by dishant-livebird** [comment]
This issue is resolved. i have mistake that distribute_options.yaml file is empty in project root directory. and after that i got another error like,

type 'Null' is not a subtype of type 'Map<String, dynamic>'
#0      loadMakeConfigYaml (package:app_package_maker/src/app_package_maker.dart:11:15)
#1      MakeDebConfigLoader.load (package:flutter_app_packager/src/makers/deb/make_deb_config.dart:365:17)
#2      FlutterAppPackager.package (package:flutter_app_packager/src/flutter_app_packager.dart:34:39)
#3      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:181:51)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)

I solved this by remove empty lines in make_config.yaml file in linux/packaging/deb directory.
