### ISSUE TITLE
EXE fail with auto_updater

### ISSUE THREAD

**Issue by kekko7072** [leanflutter/flutter_distributor#130]
I have this LMS flutter app where you can find the source code [here](https://github.com/kekko7072/lms). When i run this command ` flutter_distributor release --name dev --jobs release-windows` i get this result and fails:
```
Deleting build...                                                  100ms
Deleting ephemeral...                                               48ms
Deleting .flutter-plugins-dependencies...                            1ms
Deleting .flutter-plugins...                                         0ms
Packaging lms 1.1.0+11 as exe:
$ flutter build windows --dart-define APP_ENV=dev --dart-define FLUTTER_BUILD_NAME=1.1.0 --dart-define FLUTTER_BUILD_NUMBER=11
Resolving dependencies...
  args 2.4.0 (2.4.1 available)
  collection 1.17.1 (1.17.2 available)
  dynamic_color 1.6.2 (1.6.5 available)
  ffi 2.0.1 (2.0.2 available)
  file 6.1.4 (7.0.0 available)
  flutter_markdown 0.6.9+1 (0.6.14 available)
  flutter_spinkit 5.1.0 (5.2.0 available)
  http 0.13.5 (1.0.0 available)
  lints 2.0.1 (2.1.0 available)
  logging 1.1.1 (1.2.0 available)
  markdown 4.0.1 (7.1.0 available)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  path_provider_linux 2.1.9 (2.1.11 available)
  shared_preferences_foundation 2.2.1 (2.2.2 available)
  source_span 1.9.1 (1.10.0 available)
  sqlite3 1.11.0 (1.11.1 available)
  synchronized 3.0.1 (3.1.0 available)
  test_api 0.5.1 (0.6.0 available)
  typed_data 1.3.1 (1.3.2 available)
  url_launcher_android 6.0.24 (6.0.35 available)
  url_launcher_ios 6.1.1 (6.1.4 available)
  url_launcher_linux 3.0.3 (3.0.5 available)
  url_launcher_macos 3.0.3 (3.0.5 available)
  url_launcher_web 2.0.15 (2.0.17 available)
  url_launcher_windows 3.0.4 (3.0.6 available)
  win32 4.1.4 (5.0.2 available)
Got dependencies!

Building Windows application...                                   117,8s
√  Built build\windows\runner\Release\lms.exe (0.1MB).
{
  "config": {
    "mode": "release",
    "arguments": {
      "dart-define": {
        "APP_ENV": "dev"
      }
    }
  },
  "outputDirectory": "build/windows/runner/Release",
  "duration": 121504,
  "outputFiles": []
}
Successfully built Directory: 'build/windows/runner/Release' in 121s
$ C:\Program Files (x86)\Inno Setup 6\ISCC.exe dist/1.1.0+11/lms-1.1.0+11-windows-setup_exe.iss
Inno Setup 6 Command-Line Compiler
Copyright (C) 1997-2022 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2022 Martijn Laan. All rights reserved.
Portions Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.
https://www.innosetup.com

Compiler engine version: Inno Setup 6.2.1

Preprocessing
   Reading file: C:\Program Files (x86)\Inno Setup 6\ISPPBuiltins.iss
Error on line 78 in C:\Users\franc\Desktop\lms\dist\1.1.0+11\lms-1.1.0+11-windows-setup_exe.iss: Column 80:
Undeclared identifier: MyAppExeName.
Compile aborted.
MakeError
#0      AppPackageMakerExe._make (package:flutter_app_packager/src/makers/exe/app_package_maker_exe.dart:49:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:181:35)
<asynchronous suspension>
#2      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:320:45)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>


RELEASE FAILED in 124s
MakeError
#0      AppPackageMakerExe._make (package:flutter_app_packager/src/makers/exe/app_package_maker_exe.dart:49:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:181:35)
<asynchronous suspension>
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

```

**Comment by lijy91** [comment]
MyAppExeName appears to be undefined, please remove it
https://github.com/kekko7072/lms/blob/6e3a872e99aef04f89e0d6359c4567bf9f2ad141/windows/packaging/exe/custom_inno_script.iss#L52

**Comment by lijy91** [comment]
use EXECUTABLE_NAME

**Comment by kekko7072** [comment]
@lijy91  thank you this solved the issue.
