### ISSUE TITLE
Encountered error while creating the IPA: error: exportArchive: ipatool failed

### ISSUE THREAD

**Issue by amoLink** [leanflutter/flutter_distributor#136]
when i used flutter_distributor buil IPA, I get an error :
anbody like me , if you solved it , please let know how to do, thanks

**distribute_options.yaml**
env:
  FIR_API_TOKEN: 'xxx'

output: dist/

releases:
  - name: auto_package
    jobs:
      - name: android-apk
        package:
          platform: android
          target: apk
          build_args:
            profile: true
            target-platform: android-arm,android-arm64
        publish_to: fir
      - name: ios-ipa
        package:
          platform: ios
          target: ipa
          build_args:
            profile: true
            export-method: ad-hoc
        publish_to: fir

**error**
Encountered error while creating the IPA:
error: exportArchive: ipatool failed

Try distributing the app in Xcode: "open /aa/bb/Desktop/dev/bbb/build/ios/archive/Runner.xcarchive"
Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      BuildIosResultResolver.resolve (package:flutter_app_builder/src/builders/ios/build_ios_result.dart:16:31)
#2      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:71:27)
<asynchronous suspension>
#3      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:154:27)
<asynchronous suspension>
#4      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:327:45)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

RELEASE FAILED in 227s
Bad state: No element
#0      List.first (dart:core-patch/growable_array.dart:343:5)
#1      BuildIosResultResolver.resolve (package:flutter_app_builder/src/builders/ios/build_ios_result.dart:16:31)
#2      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:71:27)
<asynchronous suspension>
#3      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:154:27)
<asynchronous suspension>
#4      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:327:45)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

**Comment by amoLink** [comment]
Solution：
- Modify compileBitcode to NO in the exportOptions file
