### ISSUE TITLE
Build fails with an exception when building for Windows

### ISSUE THREAD

**Issue by BirjuVachhani** [leanflutter/flutter_distributor#142]
I am getting this error when running following command to build exe for Windows!

```console
flutter_distributor package --platform windows --targets exe --artifact-name=TargetMate-windows-0.6.6.exe
```

### Crash:

```console
Unhandled exception:
BuildError
BuildError
#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:154:27)
<asynchronous suspension>
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:154:27)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)

<asynchronous suspension>
```

**Comment by lijy91** [comment]
Can you provide your configuration file

**Comment by BirjuVachhani** [comment]
This was working before I added rive as dependency! So tried after removing Rive and it seems to be working just fine now! I guess it may not have anything to do with this package but it is interesting how this package throws because of it!
