### ISSUE TITLE
MakeError when packaging to AppImage for aarch64 from Raspberry Pi

### ISSUE THREAD

**Issue by nashiradeer** [leanflutter/flutter_distributor#181]
I'm trying to package to the AppImage format on a Raspberry Pi 4 with Raspbian 12 (aarch64) using the Flutter from Canonical's Snap but I'm receiving the message `MakeError: it's not a dynamic executable`. When I try to package using the same configs and command on Ubuntu (WSL 2, x86_64) 22.04 works perfectly.

<details>
<summary>flutter_distributor release --name mexanyd-desktop --jobs linux-appimage</summary>

```
===> Releasing mexanyd-desktop:linux-appimage
$ flutter clean
Packaging mexanyd_desktop 0.0.1-alpha.1 as appimage:
$ /home/nashira/snap/flutter/common/flutter/bin/flutter build linux --enable-experiment records --dart-define FLUTTER_BUILD_NAME=0.0.1-alpha.1 --dart-define FLUTTER_BUILD_NUMBER=0.0.1-alpha.1
Resolving dependencies...
Downloading packages...
Got dependencies!

Building Linux application...                                   
âœ“ Built build/linux/arm64/release/bundle/mexanyd_desktop
{
  "config": {
    "mode": "release",
    "arguments": {
      "enable-experiment": "records"
    }
  },
  "outputDirectory": "build/linux/arm64/release/bundle",
  "duration": 149269,
  "outputFiles": []
}
Successfully built Directory: 'build/linux/arm64/release/bundle' in 149s
$ cp -r build/linux/arm64/release/bundle dist/0.0.1-alpha.1/mexanyd_desktop-0.0.1-alpha.1+0.0.1-alpha.1-linux_appimage/mexanyd_desktop.AppDir
$ chmod +x dist/0.0.1-alpha.1/mexanyd_desktop-0.0.1-alpha.1+0.0.1-alpha.1-linux_appimage/mexanyd_desktop.AppDir/AppRun
$ mkdir -p dist/0.0.1-alpha.1/mexanyd_desktop-0.0.1-alpha.1+0.0.1-alpha.1-linux_appimage/mexanyd_desktop.AppDir/usr/share/icons/hicolor/128x128/apps dist/0.0.1-alpha.1/mexanyd_desktop-0.0.1-alpha.1+0.0.1-alpha.1-linux_appimage/mexanyd_desktop.AppDir/usr/share/icons/hicolor/256x256/apps
$ mkdir -p dist/0.0.1-alpha.1/mexanyd_desktop-0.0.1-alpha.1+0.0.1-alpha.1-linux_appimage/mexanyd_desktop.AppDir/usr/lib
$ ldd -d dist/0.0.1-alpha.1/mexanyd_desktop-0.0.1-alpha.1+0.0.1-alpha.1-linux_appimage/mexanyd_desktop.AppDir/lib/libflutter_linux_gtk.so
	nèŒ«o èŒ… um executè°©vel dinèŠ’mico
MakeError: 	nèŒ«o èŒ… um executè°©vel dinèŠ’mico

#0      AppPackageMakerAppImage._getSharedDependencies.<anonymous closure> (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:28:9)
<asynchronous suspension>
#1      AppPackageMakerAppImage._getSharedDependencies.<anonymous closure> (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:32:7)
<asynchronous suspension>
#2      AppPackageMakerAppImage._make (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:168:33)
<asynchronous suspension>
#3      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#4      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:327:45)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>


RELEASE FAILED in 151s
MakeError: 	nèŒ«o èŒ… um executè°©vel dinèŠ’mico

#0      AppPackageMakerAppImage._getSharedDependencies.<anonymous closure> (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:28:9)
<asynchronous suspension>
#1      AppPackageMakerAppImage._getSharedDependencies.<anonymous closure> (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:32:7)
<asynchronous suspension>
#2      AppPackageMakerAppImage._make (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:168:33)
<asynchronous suspension>
#3      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#4      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:327:45)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```
</details>

<details>
<summary>ldd -d dist/0.0.1-alpha.1/mexanyd_desktop-0.0.1-alpha.1+0.0.1-alpha.1-linux_appimage/mexanyd_desktop.AppDir/lib/libflutter_linux_gtk.so</summary>

```
	linux-vdso.so.1 (0x0000007f8718c000)
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f863a0000)
	libgtk-3.so.0 => /lib/aarch64-linux-gnu/libgtk-3.so.0 (0x0000007f85b40000)
	libgdk-3.so.0 => /lib/aarch64-linux-gnu/libgdk-3.so.0 (0x0000007f85a20000)
	libpangocairo-1.0.so.0 => /lib/aarch64-linux-gnu/libpangocairo-1.0.so.0 (0x0000007f859f0000)
	libpango-1.0.so.0 => /lib/aarch64-linux-gnu/libpango-1.0.so.0 (0x0000007f85960000)
	libatk-1.0.so.0 => /lib/aarch64-linux-gnu/libatk-1.0.so.0 (0x0000007f85910000)
	libgio-2.0.so.0 => /lib/aarch64-linux-gnu/libgio-2.0.so.0 (0x0000007f85700000)
	libgobject-2.0.so.0 => /lib/aarch64-linux-gnu/libgobject-2.0.so.0 (0x0000007f85680000)
	libglib-2.0.so.0 => /lib/aarch64-linux-gnu/libglib-2.0.so.0 (0x0000007f85520000)
	libepoxy.so.0 => /lib/aarch64-linux-gnu/libepoxy.so.0 (0x0000007f853c0000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f85390000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f852f0000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f85140000)
	/lib/ld-linux-aarch64.so.1 (0x0000007f8714f000)
	libgmodule-2.0.so.0 => /lib/aarch64-linux-gnu/libgmodule-2.0.so.0 (0x0000007f85110000)
	libharfbuzz.so.0 => /lib/aarch64-linux-gnu/libharfbuzz.so.0 (0x0000007f84ff0000)
	libcairo.so.2 => /lib/aarch64-linux-gnu/libcairo.so.2 (0x0000007f84eb0000)
	libpangoft2-1.0.so.0 => /lib/aarch64-linux-gnu/libpangoft2-1.0.so.0 (0x0000007f84e70000)
	libfontconfig.so.1 => /lib/aarch64-linux-gnu/libfontconfig.so.1 (0x0000007f84e00000)
	libfribidi.so.0 => /lib/aarch64-linux-gnu/libfribidi.so.0 (0x0000007f84dd0000)
	libcairo-gobject.so.2 => /lib/aarch64-linux-gnu/libcairo-gobject.so.2 (0x0000007f84da0000)
	libgdk_pixbuf-2.0.so.0 => /lib/aarch64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x0000007f84d50000)
	libXi.so.6 => /lib/aarch64-linux-gnu/libXi.so.6 (0x0000007f84d20000)
	libX11.so.6 => /lib/aarch64-linux-gnu/libX11.so.6 (0x0000007f84bc0000)
	libatk-bridge-2.0.so.0 => /lib/aarch64-linux-gnu/libatk-bridge-2.0.so.0 (0x0000007f84b60000)
	libXfixes.so.3 => /lib/aarch64-linux-gnu/libXfixes.so.3 (0x0000007f84b30000)
	libxkbcommon.so.0 => /lib/aarch64-linux-gnu/libxkbcommon.so.0 (0x0000007f84ac0000)
	libwayland-client.so.0 => /lib/aarch64-linux-gnu/libwayland-client.so.0 (0x0000007f84a90000)
	libwayland-cursor.so.0 => /lib/aarch64-linux-gnu/libwayland-cursor.so.0 (0x0000007f84a60000)
	libwayland-egl.so.1 => /lib/aarch64-linux-gnu/libwayland-egl.so.1 (0x0000007f84a30000)
	libXext.so.6 => /lib/aarch64-linux-gnu/libXext.so.6 (0x0000007f849f0000)
	libXcursor.so.1 => /lib/aarch64-linux-gnu/libXcursor.so.1 (0x0000007f849d0000)
	libXdamage.so.1 => /lib/aarch64-linux-gnu/libXdamage.so.1 (0x0000007f849a0000)
	libXcomposite.so.1 => /lib/aarch64-linux-gnu/libXcomposite.so.1 (0x0000007f84980000)
	libXrandr.so.2 => /lib/aarch64-linux-gnu/libXrandr.so.2 (0x0000007f84960000)
	libXinerama.so.1 => /lib/aarch64-linux-gnu/libXinerama.so.1 (0x0000007f84940000)
	libthai.so.0 => /lib/aarch64-linux-gnu/libthai.so.0 (0x0000007f84920000)
	libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007f848e0000)
	libmount.so.1 => /lib/aarch64-linux-gnu/libmount.so.1 (0x0000007f84850000)
	libselinux.so.1 => /lib/aarch64-linux-gnu/libselinux.so.1 (0x0000007f84800000)
	libffi.so.8 => /lib/aarch64-linux-gnu/libffi.so.8 (0x0000007f847d0000)
	libpcre2-8.so.0 => /lib/aarch64-linux-gnu/libpcre2-8.so.0 (0x0000007f84720000)
	libfreetype.so.6 => /lib/aarch64-linux-gnu/libfreetype.so.6 (0x0000007f84640000)
	libgraphite2.so.3 => /lib/aarch64-linux-gnu/libgraphite2.so.3 (0x0000007f84600000)
	libpixman-1.so.0 => /lib/aarch64-linux-gnu/libpixman-1.so.0 (0x0000007f84540000)
	libpng16.so.16 => /lib/aarch64-linux-gnu/libpng16.so.16 (0x0000007f844e0000)
	libxcb-shm.so.0 => /lib/aarch64-linux-gnu/libxcb-shm.so.0 (0x0000007f844b0000)
	libxcb.so.1 => /lib/aarch64-linux-gnu/libxcb.so.1 (0x0000007f84460000)
	libxcb-render.so.0 => /lib/aarch64-linux-gnu/libxcb-render.so.0 (0x0000007f84430000)
	libXrender.so.1 => /lib/aarch64-linux-gnu/libXrender.so.1 (0x0000007f84410000)
	libexpat.so.1 => /lib/aarch64-linux-gnu/libexpat.so.1 (0x0000007f843c0000)
	libjpeg.so.62 => /lib/aarch64-linux-gnu/libjpeg.so.62 (0x0000007f84340000)
	libatspi.so.0 => /lib/aarch64-linux-gnu/libatspi.so.0 (0x0000007f842e0000)
	libdbus-1.so.3 => /lib/aarch64-linux-gnu/libdbus-1.so.3 (0x0000007f84260000)
	libdatrie.so.1 => /lib/aarch64-linux-gnu/libdatrie.so.1 (0x0000007f84230000)
	libblkid.so.1 => /lib/aarch64-linux-gnu/libblkid.so.1 (0x0000007f841b0000)
	libbrotlidec.so.1 => /lib/aarch64-linux-gnu/libbrotlidec.so.1 (0x0000007f84180000)
	libXau.so.6 => /lib/aarch64-linux-gnu/libXau.so.6 (0x0000007f84160000)
	libXdmcp.so.6 => /lib/aarch64-linux-gnu/libXdmcp.so.6 (0x0000007f84140000)
	libsystemd.so.0 => /lib/aarch64-linux-gnu/libsystemd.so.0 (0x0000007f84050000)
	libbrotlicommon.so.1 => /lib/aarch64-linux-gnu/libbrotlicommon.so.1 (0x0000007f84010000)
	libbsd.so.0 => /lib/aarch64-linux-gnu/libbsd.so.0 (0x0000007f83fd0000)
	libcap.so.2 => /lib/aarch64-linux-gnu/libcap.so.2 (0x0000007f83fa0000)
	libgcrypt.so.20 => /lib/aarch64-linux-gnu/libgcrypt.so.20 (0x0000007f83e90000)
	liblzma.so.5 => /lib/aarch64-linux-gnu/liblzma.so.5 (0x0000007f83e40000)
	libzstd.so.1 => /lib/aarch64-linux-gnu/libzstd.so.1 (0x0000007f83d80000)
	liblz4.so.1 => /lib/aarch64-linux-gnu/liblz4.so.1 (0x0000007f83d30000)
	libmd.so.0 => /lib/aarch64-linux-gnu/libmd.so.0 (0x0000007f83d00000)
	libgpg-error.so.0 => /lib/aarch64-linux-gnu/libgpg-error.so.0 (0x0000007f83cb0000)
```
</details>

**Comment by judemont** [comment]
I have the same issue on debian

**Comment by jefflongo** [comment]
Also running into this issue on Ubuntu 24

**Comment by kcdev001** [comment]
Same issue on ubuntu 22.

It works fine by building the deb and rpm, but it failed on the AppImage.
