### ISSUE TITLE
On Linux arm64, an error occurs when building AppImage.

### ISSUE THREAD

**Issue by kjxbyz** [leanflutter/flutter_distributor#188]
```
wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-armhf.AppImage"
chmod +x appimagetool && mv appimagetool /usr/local/bin/
```

```
/bin/sh: 1: appimagetool: Exec format error
MakeError: /bin/sh: 1: appimagetool: Exec format error

#0      AppPackageMakerAppImage._make.<anonymous closure> (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:257:11)
<asynchronous suspension>
#1      AppPackageMakerAppImage._make (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:243:7)
<asynchronous suspension>
#2      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

Unhandled exception:
MakeError: /bin/sh: 1: appimagetool: Exec format error

#0      AppPackageMakerAppImage._make.<anonymous closure> (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:257:11)
<asynchronous suspension>
#1      AppPackageMakerAppImage._make (package:flutter_app_packager/src/makers/appimage/app_package_maker_appimage.dart:243:7)
<asynchronous suspension>
#2      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```

**Comment by kjxbyz** [comment]
This issue is caused by two reasons

1. Issue with flutter_distributor package, solution is https://github.com/kjxbyz/flutter_distributor/commit/5b135e7261f74ca72b6957f5ae7e8daf854f25c8

2. Issue with cross-platform build, solution is https://github.com/AppImage/AppImageKit/issues/1056

Best Practices:

https://github.com/picguard/picguard/actions/runs/9754956581
