### ISSUE TITLE
On Linux arm64, an error occurs when building RPM.

### ISSUE THREAD

**Issue by kjxbyz** [leanflutter/flutter_distributor#189]
```
$ rpmbuild --define _topdir /work/dist/1.0.0+1/picguard.aarch64_rpm/rpmbuild -bb /work/dist/1.0.0+1/picguard.aarch64_rpm/rpmbuild/SPECS/picguard.spec
error: No compatible architectures found for build
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:163:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

Unhandled exception:
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:163:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```

**Comment by kjxbyz** [comment]
Sorry, this is not a bug. It is because I failed to update build_arch, so the error occurs.
