### ISSUE TITLE
PathNotFoundException: PathNotFoundException: Directory listing failed

### ISSUE THREAD

**Issue by yfming93** [leanflutter/flutter_distributor#211]
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter build ipa --target lib/main.dart --export-options-plist ios/ExportOptions/AppStore/ExportOptions.plist --dart-define APP_ENV=0 --dart-define APP_CHANNEL=appstore --dart-define APP_NAME=园博士 --dart-define no-tree-shake-icons=true --dart-define FLUTTER_BUILD_NAME=1.0.0 --dart-define FLUTTER_BUILD_NUMBER=35

## exception

PathNotFoundException: PathNotFoundException: Directory listing failed, path = '/Users/mingo/Desktop/repo/ybs/build/ios/ipa/' (OS Error: No such file or directory, errno = 2)

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:228:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      OperatingSystemUtils.getDirectorySize (package:flutter_tools/src/base/os.dart:111:53)
#5      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:528:43)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```

## flutter doctor

```
[!] Flutter (Channel [user-branch], 3.22.3, on macOS 14.4.1 23E224 darwin-x64, locale zh-Hans-CN)
    ! Flutter version 3.22.3 on channel [user-branch] at /Users/mingo/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3
    • Pub download mirror https://pub.dev
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mingo/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • iPhone (mobile)    • 00008101-000304382222001E • ios            • iOS 17.4.1 21E236
    • iPhoneXsm (mobile) • 00008020-001E2C6C0168002E • ios            • iOS 16.6.1 20G81
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 127.0.6533.99

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by yfming93** [comment]
mingo@macdembp-2 ybs % flutter build ipa

Archiving com.shidai.ybs...
Automatically signing iOS for device deployment using specified development team in Xcode project: 35J33X9RQ9
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        19.8s
Xcode archive done.                                         279.0s
✓ Built build/ios/archive/Runner.xcarchive (171.5MB)

[✓] App Settings Validation
    • Version Number: 1.0.1
    • Build Number: 56
    • Display Name: 园博士
    • Deployment Target: 12.0
    • Bundle Identifier: com.shidai.ybs

To update the settings, please refer to https://docs.flutter.dev/deployment/ios

Building App Store IPA...                                          86.4s
✓ Built IPA to build/ios/ipa (58.5MB)
To upload to the App Store either:
    1. Drag and drop the "build/ios/ipa/*.ipa" bundle into the Apple Transporter macOS app https://apps.apple.com/us/app/transporter/id1450874784
    2. Run "xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey your_api_key --apiIssuer your_issuer_id".
       See "man altool" for details about how to authenticate with the App Store Connect API key.
mingo@macdembp-2 ybs %

**Comment by yfming93** [comment]
- name: app_store
    jobs:
     - name: release-appstore-ios
       package:
         platform: ios
         target: ipa
         channel: appstore
#         output-directory: build/macos/Build/Products/Release-development
         build_args:
           target: lib/main.dart
           export-options-plist: ios/ExportOptions/AppStore/ExportOptions.plist
           dart-define:
             APP_ENV: '0'
             APP_CHANNEL: 'appstore'
             APP_NAME: 'ybs'
             no-tree-shake-icons: true
       publish:
         target: appstore

**Comment by yfming93** [comment]
没有人看一下吗。
/build/ios/ipa/' (OS Error: No such file or directory, errno = 2)
变异路径 build/ios/ 下找不到 ipa
