### ISSUE TITLE
PublishError: getBuildInfo error: {code: 1081, message: error request}

### ISSUE THREAD

**Issue by yfming93** [leanflutter/flutter_distributor#212]
flutter_distributor --version
0.4.5

PublishError: PublishError: PublishError: getBuildInfo error: {code: 1081, message: error request}
#0      AppPackagePublisherPgyer.getBuildInfo (package:flutter_app_publisher/src/publishers/pgyer/app_package_publisher_pgyer.dart:136:7)
<asynchronous suspension>
#1      AppPackagePublisherPgyer.publish (package:flutter_app_publisher/src/publishers/pgyer/app_package_publisher_pgyer.dart:40:23)
<asynchronous suspension>
#2      FlutterAppPublisher.publish (package:flutter_app_publisher/src/flutter_app_publisher.dart:30:12)
<asynchronous suspension>
#3      FlutterDistributor.publish (package:flutter_distributor/src/flutter_distributor.dart:251:39)
<asynchronous suspension>
#4      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:345:13)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

**Comment by yfming93** [comment]
https://www.pgyer.com/doc/view/api?xcx=1

1081	非法请求
