### ISSUE TITLE
MakeError for bsdtar in pacman doesn't output stdout

### ISSUE THREAD

**Issue by arran4** [leanflutter/flutter_distributor#216]
All I get is this:
```
$ cp -fr build/linux/x64/release/bundle/. dist/0.0.2+2/linkwarden_mobile-0.0.2+2-linux_pacman/usr/share/linkwarden_mobile/
$ bsdtar -czf .MTREE --format=mtree --options=!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link .PKGINFO .INSTALL usr
MakeError
#0      AppPackageMakerPacman._make (package:flutter_app_packager/src/makers/pacman/app_package_maker_pacman.dart:144:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

Unhandled exception:
MakeError
#0      AppPackageMakerPacman._make (package:flutter_app_packager/src/makers/pacman/app_package_maker_pacman.dart:144:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```

**Comment by drdhaval2785** [comment]
The issue is still on in 2026. I got precisely the same error.

**Comment by drdhaval2785** [comment]
I think the issue is that 'bsdtar' is no longer a package in 'apt'. It seems to have been subsumed in libarchive-tools.

I did `apt-get install libarchive-tools`. 
And the run created the pacman output well in Github CI.

I think that this issue can be closed.

**Comment by arran4** [comment]
They still seem to be shelling out to bsdtar:

https://github.com/fastforgedev/fastforge/blob/1672a42e7dfa996777a9d2046ef5b35e783e502e/crates/app_packager/src/packagers/linux/pacman.rs#L90-L112

https://github.com/fastforgedev/fastforge/blob/1672a42e7dfa996777a9d2046ef5b35e783e502e/packages/flutter_app_packager/lib/src/makers/pacman/app_package_maker_pacman.dart#L126-L163

So on debain it's an undeclared dependency I guess? 

A "doctor" like command (IDK if they have one it's been a while) might be in order.

Although there is a native tar for dart: https://pub.dev/packages/tar No idea why they don't use that.
