### ISSUE TITLE
RPM Packaging is not working

### ISSUE THREAD

**Issue by jyo64** [leanflutter/flutter_distributor#235]
When I try to create an RPM Package for a flutter build I get the following error:

cp: cannot stat 'saber/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.xMvFh2 (%install)
    %source_date_epoch_from_changelog is set, but %changelog has no entries to take a date from
    Bad exit status from /var/tmp/rpm-tmp.xMvFh2 (%install)

RPM build warnings:

RPM build errors:
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:179:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

Unhandled exception:
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:179:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

My SPEC file does not generate an attribute called changelog even if its in my make config file. Could it be an issue with make_rpm_config.dart?

**Comment by jyo64** [comment]
Maybe because in packages/flutter_app_packager/lib/src/makers/rpm/make_rpm_config.dart changelog is being read, but not written to the SPEC file.

**Comment by MarkBenjamin** [comment]
until the bug is fixed in the codebase, personally I launch the rpm packager from a patched git checkout;
add a `changelog:` entry to your `make_config.yaml`, then the command would be (similar to)

`$ dart run /path/to/patched/git/clone/flutter_distributor/packages/flutter_distributor/bin/main.dart release --name=dev --skip-clean --jobs=release-dev-linux-rpm`

```
diff --git a/packages/flutter_app_packager/lib/src/makers/rpm/make_rpm_config.dart b/packages/flutter_app_packager/lib/src/makers/rpm/make_rpm_config.dart
index 87a8381..4134b75 100644
--- a/packages/flutter_app_packager/lib/src/makers/rpm/make_rpm_config.dart
+++ b/packages/flutter_app_packager/lib/src/makers/rpm/make_rpm_config.dart
@@ -1,6 +1,7 @@
 import 'dart:io';
 
 import 'package:flutter_app_packager/src/api/app_package_maker.dart';
+import 'package:intl/intl.dart';
 
 class MakeRPMConfig extends MakeConfig {
   MakeRPMConfig({
@@ -105,6 +106,11 @@ class MakeRPMConfig extends MakeConfig {
 
   @override
   Map<String, dynamic> toJson() {
+	print("changelog=$changelog");
+	DateTime now = DateTime.now();
+	String formattedDate = DateFormat('EEE MMM dd yyyy').format(now);
+	final rpmVersion = appVersion.toString();
+	print("running github patched version");
     return {
       'SPEC': {
         'preamble': {
@@ -131,12 +137,13 @@ class MakeRPMConfig extends MakeConfig {
             'mkdir -p %{buildroot}%{_datadir}/applications',
             'mkdir -p %{buildroot}%{_datadir}/metainfo',
             'mkdir -p %{buildroot}%{_datadir}/pixmaps',
-            'cp -r %{name}/* %{buildroot}%{_datadir}/%{name}',
+            'cp -r ../%{name}/* %{buildroot}%{_datadir}/%{name}',
             'ln -s %{_datadir}/%{name}/%{name} %{buildroot}%{_bindir}/%{name}',
-            'cp -r %{name}.desktop %{buildroot}%{_datadir}/applications',
-            'cp -r %{name}.png %{buildroot}%{_datadir}/pixmaps',
-            'cp -r %{name}*.xml %{buildroot}%{_datadir}/metainfo || :',
+            'cp -r ../%{name}.desktop %{buildroot}%{_datadir}/applications',
+            'cp -r ../%{name}.png %{buildroot}%{_datadir}/pixmaps',
+            'cp -r ../%{name}*.xml %{buildroot}%{_datadir}/metainfo || :',
             'update-mime-database %{_datadir}/mime &> /dev/null || :',
+            '%undefine __brp_add_determinism',
           ].join('\n'),
           '%postun': ['update-mime-database %{_datadir}/mime &> /dev/null || :']
               .join('\n'),
@@ -150,6 +157,7 @@ class MakeRPMConfig extends MakeConfig {
         'inline-body': {
           '%defattr': '(-,root,root)',
           '%attr': '(4755, root, root) %{_datadir}/pixmaps/%{name}.png',
+          '%changelog': '\n* $formattedDate $packager <$packagerEmail> - $rpmVersion\n- $changelog',
         },
       },
       'DESKTOP': {
diff --git a/packages/flutter_app_packager/pubspec.yaml b/packages/flutter_app_packager/pubspec.yaml
index be636c2..2aa5512 100644
--- a/packages/flutter_app_packager/pubspec.yaml
+++ b/packages/flutter_app_packager/pubspec.yaml
@@ -10,6 +10,7 @@ dependencies:
   archive: ^3.6.1
   io: ^1.0.3
   liquid_engine: ^0.2.2
+  intl: ^0.20.0
   msix: ^3.16.6
   mustache_template: ^2.0.0
   path: ^1.8.1
diff --git a/packages/flutter_distributor/pubspec.yaml b/packages/flutter_distributor/pubspec.yaml
index 0ea07e6..0f147a4 100644
--- a/packages/flutter_distributor/pubspec.yaml
+++ b/packages/flutter_distributor/pubspec.yaml
@@ -14,8 +14,8 @@ environment:
   sdk: ">=2.16.0 <4.0.0"
 
 dependencies:
-  unified_distributor: ^0.1.1
-
+  unified_distributor:
+    path: ../unified_distributor
 dev_dependencies:
   mostly_reasonable_lints: ^0.1.2
 
diff --git a/packages/unified_distributor/pubspec.yaml b/packages/unified_distributor/pubspec.yaml
index a7c68a3..b7c6b8d 100644
--- a/packages/unified_distributor/pubspec.yaml
+++ b/packages/unified_distributor/pubspec.yaml
@@ -19,8 +19,9 @@ dependencies:
   charset: ^2.0.1
   dio: ^5.3.4
   flutter_app_builder: ^0.4.6
-  flutter_app_packager: ^0.4.6
   flutter_app_publisher: ^0.4.6
+  flutter_app_packager:
+    path: ../flutter_app_packager
   logging: ^1.0.2
   path: ^1.8.1
   pubspec_parse: ^1.1.0
```
(you'll need to `pub get` in the relevant package subdirectories too)
The relative paths for the `flutter_app_packager` pubspec dependency as well as now the `unified_distributor` just make sure it won't launch the `pub global activate`d flutter_distributor / fastforge

**Comment by kjxbyz** [comment]
Building an rpm package on Ubuntu and getting an error during installation.

```
Error: 
 Problem: conflicting requests
  - nothing provides libcurl.so.4(CURL_OPENSSL_4)(64bit) needed by picguard-5.0.3+459-459.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)

```

Building rpm package on fedora:40, error reported during building.

```
*
* WARNING: 'check-rpaths' detected a broken RPATH OR RUNPATH and will cause
*          'rpmbuild' to fail. To ignore these errors, you can set the
*          '$QA_RPATHS' environment variable which is a bitmask allowing the
*          values below. The current value of QA_RPATHS is 0x0011.
*
*    0x0001 ... standard RPATHs (e.g. /usr/lib); such RPATHs are a minor
*               issue but are introducing redundant searchpaths without
*               providing a benefit. They can also cause errors in multilib
*               environments.
*    0x0002 ... invalid RPATHs; these are RPATHs which are neither absolute
*               nor relative filenames and can therefore be a SECURITY risk
*    0x0004 ... insecure RPATHs; these are relative RPATHs which are a
*               SECURITY risk
*    0x0008 ... the special '$ORIGIN' RPATHs are appearing after other
*               RPATHs; this is just a minor issue but usually unwanted
*    0x0010 ... the RPATH is empty; there is no reason for such RPATHs
*               and they cause unneeded work while loading libraries
*    0x0020 ... an RPATH references '..' of an absolute path; this will break
*               the functionality when the path before '..' is a symlink
*          
*
* Examples:
* - to ignore standard and empty RPATHs, execute 'rpmbuild' like
*   $ QA_RPATHS=$(( 0x0001|0x0010 )) rpmbuild my-package.src.rpm
* - to check existing files, set $RPM_BUILD_ROOT and execute check-rpaths like
*   $ RPM_BUILD_ROOT=<top-dir> /usr/lib/rpm/check-rpaths
*  
*******************************************************************************
ERROR   0002: file '/usr/share/picguard/lib/libdesktop_drop_plugin.so' contains an invalid runpath '/__w/picguard/picguard/linux/flutter/ephemeral' in [/__w/picguard/picguard/linux/flutter/ephemeral]
ERROR   0002: file '/usr/share/picguard/lib/liburl_launcher_linux_plugin.so' contains an invalid runpath '/__w/picguard/picguard/linux/flutter/ephemeral' in [/__w/picguard/picguard/linux/flutter/ephemeral]
ERROR   0002: file '/usr/share/picguard/lib/libfile_selector_linux_plugin.so' contains an invalid runpath '/__w/picguard/picguard/linux/flutter/ephemeral' in [/__w/picguard/picguard/linux/flutter/ephemeral]
ERROR   0002: file '/usr/share/picguard/lib/libfile_saver_plugin.so' contains an invalid runpath '/__w/picguard/picguard/linux/flutter/ephemeral' in [/__w/picguard/picguard/linux/flutter/ephemeral]
ERROR   0002: file '/usr/share/picguard/lib/libnb_utils_plugin.so' contains an invalid runpath '/__w/picguard/picguard/linux/flutter/ephemeral' in [/__w/picguard/picguard/linux/flutter/ephemeral]
ERROR   0002: file '/usr/share/picguard/lib/libdartjni.so' contains an invalid runpath '/__t/Java_Temurin-Hotspot_jdk/17.0.16-8/x64/lib/server' in [/__t/Java_Temurin-Hotspot_jdk/17.0.16-8/x64/lib/server]
ERROR   0002: file '/usr/share/picguard/lib/libtray_manager_plugin.so' contains an invalid runpath '/__w/picguard/picguard/linux/flutter/ephemeral' in [/__w/picguard/picguard/linux/flutter/ephemeral]
error: Bad exit status from /var/tmp/rpm-tmp.Eg8ers (%install)
    source_date_epoch_from_changelog set but %changelog is missing
RPM build warnings:
    Bad exit status from /var/tmp/rpm-tmp.Eg8ers (%install)
RPM build errors:
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:179:7)
<asynchronous suspension>
#1      UnifiedDistributor.package (package:unified_distributor/src/unified_distributor.dart:197:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      main (file:///github/home/.pub-cache/hosted/pub.dev/fastforge-0.6.6/bin/main.dart:10:10)
<asynchronous suspension>
Unhandled exception:
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:179:7)
<asynchronous suspension>
#1      UnifiedDistributor.package (package:unified_distributor/src/unified_distributor.dart:197:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      main (file:///github/home/.pub-cache/hosted/pub.dev/fastforge-0.6.6/bin/main.dart:10:10)
<asynchronous suspension>
```

**Comment by kjxbyz** [comment]
`'cp -r ../%{name}/* %{buildroot}%{_datadir}/%{name}',`

cp: cannot stat '../picguard/*': No such file or directory

**Comment by MarkBenjamin** [comment]
As I recall, that error is not critical; what is the full (relevant part of the) console trace from the patched invocation?

**Comment by kjxbyz** [comment]
> As I recall, that error is not critical; what is the full (relevant part of the) console trace from the patched invocation?

```
Run export SENTRY_NATIVE_BACKEND=breakpad


⠋ Checking for updates...
⠙ Checking for updates...
⠹ Checking for updates...
                                 
🎉 You are using the latest version (0.6.6)

Packaging picguard 5.0.3+459 as rpm:
$ /__t/flutter/stable-3.35.5-x64/bin/flutter build linux --dart-define-from-file .env --target lib/main_free.dart --dart-define FLUTTER_BUILD_NAME=5.0.3 --dart-define FLUTTER_BUILD_NUMBER=459
Resolving dependencies...
Downloading packages...
  _fe_analyzer_shared 89.0.0 (90.0.0 available)
  analyzer 8.2.0 (8.3.0 available)
  build 4.0.1 (4.0.2 available)
  characters 1.4.0 (1.4.1 available)
  connectivity_plus 6.1.5 (7.0.0 available)
  flutter_plugin_android_lifecycle 2.0.30 (2.0.31 available)
  fluttertoast 8.2.14 (9.0.0 available)
  image_picker_android 0.8.13+3 (0.8.13+4 available)
  material_color_utilities 0.11.1 (0.13.0 available)
  meta 1.16.0 (1.17.0 available)
  objective_c 8.0.0 (8.1.0 available)
  path_provider_android 2.2.18 (2.2.19 available)
  shared_preferences_android 2.4.14 (2.4.15 available)
  test_api 0.7.6 (0.7.7 available)
  url_launcher_android 6.3.23 (6.3.24 available)
Got dependencies!
15 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Building Linux application...                                   
✓ Built build/linux/x64/release/bundle/picguard
{
  "config": {
    "mode": "release",
    "arguments": {
      "dart-define": {},
      "dart-define-from-file": ".env",
      "target": "lib/main_free.dart"
    }
  },
  "outputDirectory": "build/linux/x64/release/bundle",
  "duration": 60333,
  "outputFiles": []
}
Successfully built Directory: 'build/linux/x64/release/bundle' in 60s
$ cp -r build/linux/x64/release/bundle/picguard /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard
$ cp -r build/linux/x64/release/bundle/lib /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard
$ cp -r build/linux/x64/release/bundle/data /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libsentry.so

$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libapp.so

$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libdesktop_drop_plugin.so
/__w/picguard/picguard/linux/flutter/ephemeral
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/liburl_launcher_linux_plugin.so
/__w/picguard/picguard/linux/flutter/ephemeral
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libfile_selector_linux_plugin.so
/__w/picguard/picguard/linux/flutter/ephemeral
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libflutter_linux_gtk.so
$ORIGIN
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libfile_saver_plugin.so
/__w/picguard/picguard/linux/flutter/ephemeral
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libnb_utils_plugin.so
/__w/picguard/picguard/linux/flutter/ephemeral
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libdartjni.so
/__t/Java_Temurin-Hotspot_jdk/17.0.16-8/x64/lib/server
$ patchelf --print-rpath /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD/picguard/lib/libtray_manager_plugin.so
/__w/picguard/picguard/linux/flutter/ephemeral
$ rpmbuild --define _topdir /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild -bb /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/SPECS/picguard.spec
setting SOURCE_DATE_EPOCH=1760227200
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.LhlTag
+ umask 022
+ cd /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILD
+ '[' /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64 '!=' / ']'
+ rm -rf /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64
++ dirname /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64
+ mkdir -p /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT
+ mkdir /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -I/usr/lib64/gfortran/modules '
+ export FCFLAGS
+ VALAFLAGS=-g
+ export VALAFLAGS
+ RUSTFLAGS='-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Cstrip=none -Cforce-frame-pointers=yes -Clink-arg=-specs=/usr/lib/rpm/redhat/redhat-package-notes --cap-lints=warn'
+ export RUSTFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ mkdir -p /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64/usr/bin
+ mkdir -p /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64/usr/share/picguard
+ mkdir -p /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64/usr/share/applications
+ mkdir -p /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64/usr/share/metainfo
+ mkdir -p /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64/usr/share/pixmaps
+ cp -r '../picguard/*' /__w/picguard/picguard/dist/5.0.3+459/picguard-5.0.3.459-linux-amd64_rpm/rpmbuild/BUILDROOT/picguard-5.0.3+459-459.fc40.x86_64/usr/share/picguard
cp: cannot stat '../picguard/*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.LhlTag (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.LhlTag (%install)
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:179:7)
<asynchronous suspension>
#1      UnifiedDistributor.package (package:unified_distributor/src/unified_distributor.dart:197:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      main (file:///github/home/.pub-cache/git/fastforge-acc876dd08f04c2c1e154733715b4aeca14750d7/packages/fastforge/bin/main.dart:10:10)
<asynchronous suspension>

Unhandled exception:
MakeError
#0      AppPackageMakerRPM._make (package:flutter_app_packager/src/makers/rpm/app_package_maker_rpm.dart:179:7)
<asynchronous suspension>
#1      UnifiedDistributor.package (package:unified_distributor/src/unified_distributor.dart:197:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      main (file:///github/home/.pub-cache/git/fastforge-acc876dd08f04c2c1e154733715b4aeca14750d7/packages/fastforge/bin/main.dart:10:10)
<asynchronous suspension>
```

**Comment by MarkBenjamin** [comment]
Is that a patched invocation? There's no trace of `running github patched version`; have you added `%undefine __brp_add_determinism` that as I recall matters too?

There may be upstream changes that need accounting for too, NB my patch was current as of May 4 this year, it would be worth checking the git history for relevant changes

I should add that it's possible the rpmbuild version in Fedora 40 is before the directory changes happened, too

**Comment by kjxbyz** [comment]
@MarkBenjamin 

<img width="708" height="717" alt="Image" src="https://github.com/user-attachments/assets/32f7b375-13f7-4814-9da7-82c55a941f04" />

**Comment by MSOB7YY** [comment]
## for anyone looking for a temp fix, use my fork like this:

```
dart pub global deactivate fastforge_workspace
dart pub global deactivate fastforge
dart pub global activate --source git https://github.com/MSOB7YY/fastforge.git
dart pub global activate --source git https://github.com/MSOB7YY/fastforge.git --git-path "packages/fastforge"
```
---
<sub>credits to @MarkBenjamin for showing the required changes </sub>

**Comment by VillagerTom** [comment]
I was about to submit a new issue but found this. Following is the analysis from Big Pickle.

## Bug Description

The RPM maker `%install` section uses relative paths (`%{name}/*`, `%{name}.desktop`, `%{name}.png`), which assume the cwd's direct children include `{name}/`, `{name}.desktop`, and `{name}.png`. This broke starting from **RPM 4.20.0** due to [rpm-software-management/rpm#2885](https://github.com/rpm-software-management/rpm/pull/2885), which introduced an rpm-controlled per-build directory. The `%{_builddir}` macro is now overridden from `%{_topdir}/BUILD` to `%{_topdir}/BUILD/%{NAME}-%{VERSION}-%{_arch}/` at spec parse time, and `%install` runs inside this new directory — adding an extra directory level between `BUILD/` and the source files.

**Affected RPM versions:** >= 4.20.0 (including 6.0.x) — e.g., Fedora 40+, openSUSE Tumbleweed, Arch, Ubuntu 26.04
**Unaffected:** <= 4.19.x — e.g., Ubuntu 22.04, Fedora 39 and earlier

## Directory Structure Comparison

```
# RPM <= 4.19.x (old):
BUILD/
  name-version/          ← cwd during %install (if %setup used)
    ...sources...

# RPM >= 4.20.x (new):
BUILD/
  name-ver-arch/         ← NEW intermediate dir (rpm-controlled per-build dir)
    BUILDROOT/
    name-version/        ← cwd during %install
      ...sources...
```

Without `%setup` (as in fastforge's generated spec):
- **Old:** cwd = `%{_topdir}/BUILD/`
- **New:** cwd = `%{_topdir}/BUILD/%{NAME}-%{VERSION}-%{_arch}/`

## Reproduction

```bash
flutter create test_rpm
cd test_rpm
mkdir -p linux/packaging/rpm
# Create minimal make_config.yaml with icon
fastforge package --platform linux --target rpm
```

## Error Output

```
正在执行(%install)：/bin/sh -e /var/tmp/rpm-tmp.XXXXX

+ umask 022

+ cd .../BUILD/test_rpm-1.0.0+1-x86_64

+ /usr/bin/rm -rf ...

+ /usr/bin/mkdir -p ...
...


+ cp -r 'test_rpm/*' .../BUILDROOT/usr/share/test_rpm
cp: cannot stat 'test_rpm/*': No such file or directory
```

The `cp -r %{name}/*` glob also fails to expand because the shell cannot resolve the path from the new cwd.

## Root Cause

In `make_rpm_config.dart`, the `%install` section:

```dart
'cp -r %{name}/* %{buildroot}%{_datadir}/%{name}',
'ln -s %{_datadir}/%{name}/%{name} %{buildroot}%{_bindir}/%{name}',
'cp -r %{name}.desktop %{buildroot}%{_datadir}/applications',
'cp -r %{name}.png %{buildroot}%{_datadir}/pixmaps',
```

On RPM >= 4.20.x, the cwd is `BUILD/%{NAME}-%{VERSION}-%{_arch}/`, so `cp -r %{name}/*` looks for `{name}/` as a direct child of this directory, but it doesn't exist there — the source files are at a different level in the tree.

## Why This Bug Is Easy to Miss

- **Ubuntu 22.04/24.04** (GitHub Actions runner) ships RPM <= 4.19.x, where the per-build directory is not used — builds pass.
- **Ubuntu 26.04** (GitHub Actions runner) ships RPM 6.0.1 — builds fail with this bug.
- Older machines with RPM <= 4.19.x are unaffected.

This explains why the bug may go unnoticed in CI but reproduce locally on newer systems.

## Proposed Fix

Use `%{_topdir}/BUILD/%{name}/` absolute paths:

```dart
'cp -r %{_topdir}/BUILD/%{name}/* %{buildroot}%{_datadir}/%{name}',
'cp -r %{_topdir}/BUILD/%{name}.desktop %{buildroot}%{_datadir}/applications',
'cp -r %{_topdir}/BUILD/%{name}.png %{buildroot}%{_datadir}/pixmaps',
```

This is compatible with both RPM <= 4.19.x and >= 4.20.x.

## Environment

- fastforge 0.6.9
- RPM 6.0.1 (reproducible on any RPM >= 4.20.x)
- Flutter 3.44.x

**Comment by VillagerTom** [comment]
The build was passed on my Arch Linux with the patch above.

**Comment by eximius313** [comment]
> Building an rpm package on Ubuntu and getting an error during installation.
> 
> ```
> Error: 
>  Problem: conflicting requests
>   - nothing provides libcurl.so.4(CURL_OPENSSL_4)(64bit) needed by picguard-5.0.3+459-459.x86_64 from @commandline
> (try to add '--skip-broken' to skip uninstallable packages)
> ```
> 

@kjxbyz - your issue might be fixed in: https://github.com/fastforgedev/fastforge/issues/330

> ## Proposed Fix
> Use `%{_topdir}/BUILD/%{name}/` absolute paths:
> 
> 'cp -r %{_topdir}/BUILD/%{name}/* %{buildroot}%{_datadir}/%{name}',
> 'cp -r %{_topdir}/BUILD/%{name}.desktop %{buildroot}%{_datadir}/applications',
> 'cp -r %{_topdir}/BUILD/%{name}.png %{buildroot}%{_datadir}/pixmaps',
> This is compatible with both RPM <= 4.19.x and >= 4.20.x.

@VillagerTom - it sound a little bit as: https://github.com/fastforgedev/fastforge/issues/314

**Comment by kjxbyz** [comment]
It works for me.
