### ISSUE TITLE
Code execution failed (flutter sdk 3.27.0)

### ISSUE THREAD

**Issue by sw517227087** [leanflutter/flutter_distributor#238]
When my flutter sdk version is upgraded to 3.27.0, an error occurs when running the code

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (7 available)            
    ! Error: Browsing on the local area network for 伍吉的iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

Error Code:
Downloading packages... . 
> _discoveryapis_commons 1.0.7 (was 1.0.6)
> _fe_analyzer_shared 77.0.0 (was 72.0.0)
> _macros 0.3.3 from sdk dart (was 0.3.2 from sdk dart)
> analyzer 7.0.0 (was 6.7.0)
> ansicolor 2.0.3 (was 2.0.2)
> archive 3.6.1 (was 3.5.1) (4.0.1 available)
> args 2.6.0 (was 2.5.0)
> asn1lib 1.5.8 (was 1.5.3)
> async 2.12.0 (was 2.11.0)
> boolean_selector 2.1.2 (was 2.1.1)
> cli_util 0.4.2 (was 0.4.1)
> clock 1.1.2 (was 1.1.1)
> collection 1.19.1 (was 1.18.0)
> convert 3.1.2 (was 3.1.1)
> coverage 1.11.1 (was 1.8.0)
> crypto 3.0.6 (was 3.0.3)
> dart_jsonwebtoken 2.14.2 (was 2.14.1)
  dependency_validator 3.2.3 (4.1.2 available)
> dio 5.7.0 (was 5.4.3+1)
+ dio_web_adapter 2.0.0
> file 7.0.1 (was 7.0.0)
> get_it 7.7.0 (was 7.6.8) (8.0.3 available)
> google_identity_services_web 0.3.3 (was 0.3.1+1)
> googleapis 13.2.0 (was 13.1.0)
> googleapis_auth 1.6.0 (was 1.5.1)
> http 1.2.2 (was 1.2.1)
> http_parser 4.1.1 (was 4.0.2)
> image 4.3.0 (was 4.1.7) (4.5.0 available)
> io 1.0.5 (was 1.0.4)
> logging 1.3.0 (was 1.2.0)
> macros 0.1.3-main.0 (was 0.1.2-main.4)
  matcher 0.12.16+1 (0.12.17 available)
> meta 1.16.0 (was 1.15.0)
> mime 1.0.6 (was 1.0.5) (2.0.0 available)
> msix 3.16.8 (was 3.16.7)
> package_config 2.1.1 (was 2.1.0)
> parse_app_package 0.4.5 (was 0.4.0)
> path 1.9.1 (was 1.9.0)
  pretty_dio_logger 1.3.1 (1.4.0 available)
> pub_semver 2.1.5 (was 2.1.4)
> pubspec_parse 1.3.0 (was 1.2.3)
  qiniu_sdk_base 0.5.2 (0.7.0 available)
> shelf 1.4.2 (was 1.4.1)
> shelf_static 1.1.3 (was 1.1.2)
> shelf_web_socket 2.0.1 (was 2.0.0)
> shell_executor 0.1.6 (was 0.1.5)
> source_map_stack_trace 2.1.2 (was 2.1.1)
> source_maps 0.10.13 (was 0.10.12)
> source_span 1.10.1 (was 1.10.0)
> stack_trace 1.12.0 (was 1.11.1)
> string_scanner 1.4.0 (was 1.2.0)
> test 1.25.12 (was 1.25.5)
> test_api 0.7.4 (was 0.7.1)
> test_core 0.6.8 (was 0.6.2)
> typed_data 1.4.0 (was 1.3.2)
  uuid 3.0.7 (4.5.1 available)
> vm_service 15.0.0 (was 14.2.2)
> web 1.1.0 (was 0.5.1)
> web_socket 0.1.6 (was 0.1.4)
> web_socket_channel 3.0.1 (was 3.0.0)
These packages are no longer being depended on:
- app_package_parser 0.2.4
Would change 56 dependencies in `/Users/songwei/Desktop/code/flutter_distributor/packages/flutter_distributor`.
9 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
The current activation of `flutter_distributor` is not compatible with your current SDK.

Try reactivating the package.
`dart pub global activate flutter_distributor`

**Comment by ThinkerJack** [comment]
也出现了这个问题，运行dart pub global activate flutter_distributor后，出现错误
Error on line 15 in D:\xx_exe.iss: 系统找不到指定的路径。

Compile aborted.
MakeError
#0      AppPackageMakerExe._make (package:flutter_app_packager/src/makers/exe/app_package_maker_exe.dart:49:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

Unhandled exception:
MakeError
#0      AppPackageMakerExe._make (package:flutter_app_packager/src/makers/exe/app_package_maker_exe.dart:49:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

**Comment by ThinkerJack** [comment]
当我的flutter sdk版本升级到3.27.0时，运行flutter_distributor package --platform windows --targets exe报错
