### ISSUE TITLE
pgyer 上传成功但是显示失败

### ISSUE THREAD

**Issue by yy1300326388** [leanflutter/flutter_distributor#3]
pgyer 上传成功但是显示失败，实际已上传成功

## 执行命令

```
flutter_distributor publish --path dist/1.8.0+314/app-1.8.0+314-android.apk --targets pgyer
```

## 结果
```
Publish to pgyer: 100%
Unhandled exception:
PublishError: 0 -
#0      AppPackagePublisherPgyer.publish (package:app_package_publisher_pgyer/src/app_package_publisher_pgyer.dart:43:7)
<asynchronous suspension>
#1      FlutterAppPublisher.publish (package:flutter_app_publisher/src/flutter_app_publisher.dart:21:12)
<asynchronous suspension>
#2      FlutterDistributor.publish (package:flutter_distributor/src/flutter_distributor.dart:82:37)
<asynchronous suspension>
#3      CommandPublish.run (file:///Users/zero/.pub-cache/hosted/pub.flutter-io.cn/flutter_distributor-0.0.6/bin/command_publish.dart:24:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#5      main (file:///Users/zero/.pub-cache/hosted/pub.flutter-io.cn/flutter_distributor-0.0.6/bin/main.dart:18:3)
<asynchronous suspension>
```

### 数据返回

- 正常成功

```json
{
    "code": 0,
    "message": "",
    "data": {
        "buildKey": "9ef94134e9efd5e3850146f7ffd4bdb7",
        "buildType": "2",
        "buildIsFirst": "0",
        "buildIsLastest": "1",
        "buildFileKey": "36c9c143a2204cb77601c0e43c3bb063.apk",
        "buildFileName": "app-1.8.0+314-android.apk",
        "buildFileSize": "17879795",
        "buildName": "xxx",
        "buildVersion": "1.8.0",
        "buildVersionNo": "314",
        "buildBuildVersion": "251",
        "buildIdentifier": "xxxx",
        "buildIcon": "eec62155ff03cde14f628bd472a30d26",
        "buildDescription": "",
        "buildUpdateDescription": "",
        "buildScreenshots": "",
        "buildShortcutUrl": "xgja",
        "buildCreated": "2021-12-24 12:52:56",
        "buildUpdated": "2021-12-24 12:52:56",
        "buildQRCodeURL": "https://www.pgyer.com/app/qrcodeHistory/e68ed2fb6e4224eb85ac15c8291d9de1b25103893accffa146c6f14739746027"
    }
}
```

- 失败

```json
{
    "code": 1002,
    "message": "_api_key not found"
}
```

https://github.com/leanflutter/flutter_distributor/blob/bf2655533fb28c8e80dd198488d887e5d5f49e5c/packages/app_package_publisher_pgyer/lib/src/app_package_publisher_pgyer.dart#L40-L48

- 第 41 行应该判断` code != 0`
- 第 47 行应该取 `response.data!['data']['buildShortcutUrl']` ，并且应该拼接：`http://www.pgyer.com/`

### url 取 `buildShortcutUrl` 还是 `buildKey` ？
- `buildKey` 是指当前 build 的版本，`buildShortcutUrl`  是整个引用，大多情况下是相等的，但是多人同时打包情况，就会不同
- 如果 `buildKey` 是最新的版本会自动重定向到 `buildShortcutUrl`
- 所以这里应该取  `buildKey` 拼接 `'http://www.pgyer.com/$buildKey'`

## 参考文档

- [https://www.pgyer.com/doc/view/api#uploadApp](https://www.pgyer.com/doc/view/api#uploadApp)

**Comment by yy1300326388** [comment]
稍后➕PR

**Comment by lijy91** [comment]
已合并 PR #4
