### ISSUE TITLE
Null check operator used on a null value 

### ISSUE THREAD

**Issue by yy1300326388** [leanflutter/flutter_distributor#6]
## 执行操作
```
flutter_distributor publish --path dist/1.8.0+314/app-1.8.0+314-android.apk --targets fir
# or
flutter_distributor publish --path dist/1.8.0+314/app-1.8.0+314-android.apk --targets pgyer
```
## 错误

```
Unhandled exception:
Null check operator used on a null value
#0      AppPackagePublisherFir.publish (package:app_package_publisher_fir/src/app_package_publisher_fir.dart:59:60)
#1      FlutterAppPublisher.publish (package:flutter_app_publisher/src/flutter_app_publisher.dart:21:28)
#2      FlutterDistributor.publish (package:flutter_distributor/src/flutter_distributor.dart:82:54)
#3      CommandPublish.run (file:///Users/zero/project/zero/dart/flutter_distributor/packages/flutter_distributor/bin/command_publish.dart:24:23)
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#5      main (file:///Users/zero/project/zero/dart/flutter_distributor/packages/flutter_distributor/bin/main.dart:18:16)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

## 错误情况
如果我没有把以下 `key` 添加到环境变量中就会报错

- 环境变量 Key：`FIR_API_TOKEN、PGYER_API_TOKEN`

**Comment by yy1300326388** [comment]
## 处理方法

将对于的 key 添加到环境变量中

-  FIR_API_TOKEN
```
export FIR_API_TOKEN="xxx"
```

- PGYER_API_TOKEN
```
export PGYER_API_TOKEN="xxx"
```

**Comment by yy1300326388** [comment]
代码会做如下优化
```
String? apiToken = Platform.environment['PGYER_API_TOKEN'];

if (apiToken?.isEmpty ?? true) {
  throw PublishError(
      'Please set `PGYER_API_TOKEN` to your environment, e.g. '
      'export PGYER_API_TOKEN="xxx"');
}
```

**Comment by lijy91** [comment]
```dart
String? apiToken = Platform.environment[kEnvFirApiToken];
if ((apiToken ?? '').isEmpty) {
  throw PublishError('Missing `$kEnvFirApiToken` environment variable.');
}

PublishFirConfig publishConfig = PublishFirConfig(
  apiToken: apiToken!,
);
```

**Comment by lijy91** [comment]
已合并 PR #7
