### ISSUE TITLE
构建dmg每次都报错

### ISSUE THREAD

**Issue by springeye** [leanflutter/flutter_distributor#82]
```
flutter build macos --dart-define FLUTTER_BUILD_NAME=1.0.0 --dart-define FLUTTER_BUILD_NUMBER=1
Running "flutter pub get" in oplin...
2,342ms

💪 Building with sound null safety 💪
Running pod install...
714ms
Building macOS application...

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-001870521A02801E }
{ platform:macOS, arch:x86_64, id:00006001-001870521A02801E }
Successfully builded Directory: 'build/macos/Build/Products/Release'
Unhandled exception:
ProcessException: No such file or directory
  Command: appdmg dist/1.0.0+1/oplin-1.0.0+1-macos_dmg/make_config.json dist/1.0.0+1/oplin-1.0.0+1-macos.dmg
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      AppPackageMakerDmg.make (package:app_package_maker_dmg/src/app_package_maker_dmg.dart:65:38)
<asynchronous suspension>
#3      FlutterAppPackager.package (package:flutter_app_packager/src/flutter_app_packager.dart:42:12)
<asynchronous suspension>
#4      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:173:35)
<asynchronous suspension>
#5      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:309:43)
<asynchronous suspension>
#6      CommandRelease.run (file:///Users/develop/.pub-cache/hosted/pub.flutter-io.cn/flutter_distributor-0.2.4/bin/command_release.dart:33:5)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      main (file:///Users/develop/.pub-cache/hosted/pub.flutter-io.cn/flutter_distributor-0.2.4/bin/main.dart:38:3)
<asynchronous suspension>

```

**Comment by lijy91** [comment]
目前依赖了 appdmg ，请根据文档先安装它

**Comment by lijy91** [comment]
https://distributor.leanflutter.org/zh/docs/makers/dmg
