### ISSUE TITLE
上传appcenter指定 appcenter-distribution-group时报错。

### ISSUE THREAD

**Issue by KaleFoxit** [leanflutter/flutter_distributor#89]
如题，apk文件可以上传成功，但是不能指定到distribution-group。
<img width="1214" alt="WX20220810-212857@2x" src="https://user-images.githubusercontent.com/93690763/183913952-92955f6e-6d7c-49a5-aaa2-146cdec4f03d.png">

使用命令：
flutter_distributor publish \
            --path test.apk \
            --targets appcenter \
            --appcenter-owner-name *** \
            --appcenter-app-name *** \
            --appcenter-distribution-group beta
 
```
Unhandled exception:
DioError [DioErrorType.response]: Http status error [400]
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
#2      DioMixin.patch (package:dio/src/dio_mixin.dart:249:12)
#3      AppPackagePublisherAppCenter._applyingDestinationToRelease (package:app_package_publisher_appcenter/src/app_package_publisher_appcenter.dart:247:33)
#4      AppPackagePublisherAppCenter.publish (package:app_package_publisher_appcenter/src/app_package_publisher_appcenter.dart:106:13)
<asynchronous suspension>
#5      FlutterAppPublisher.publish (package:flutter_app_publisher/src/flutter_app_publisher.dart:33:12)
<asynchronous suspension>
#6      FlutterDistributor.publish (package:flutter_distributor/src/flutter_distributor.dart:243:39)
<asynchronous suspension>
#7      CommandPublish.run (file:///Users/kale/.pub-cache/hosted/pub.dartlang.org/flutter_distributor-0.2.4/bin/command_publish.dart:68:5)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#9      main (file:///Users/kale/.pub-cache/hosted/pub.dartlang.org/flutter_distributor-0.2.4/bin/main.dart:38:3)
<asynchronous suspension>

#0      AppPackagePublisherAppCenter.publish (package:app_package_publisher_appcenter/src/app_package_publisher_appcenter.dart:113:7)
<asynchronous suspension>
#1      FlutterAppPublisher.publish (package:flutter_app_publisher/src/flutter_app_publisher.dart:33:12)
<asynchronous suspension>
#2      FlutterDistributor.publish (package:flutter_distributor/src/flutter_distributor.dart:243:39)
<asynchronous suspension>
#3      CommandPublish.run (file:///Users/kale/.pub-cache/hosted/pub.dartlang.org/flutter_distributor-0.2.4/bin/command_publish.dart:68:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#5      main (file:///Users/kale/.pub-cache/hosted/pub.dartlang.org/flutter_distributor-0.2.4/bin/main.dart:38:3)
<asynchronous suspension>

**Comment by lijy91** [comment]
请确定已经在 appcenter 的后台创建了相应的 Group
